### ISSUE TITLE
[Feature Request] Buscar a letra da música atual (por padrão) caso não seja informado um parâmetro (tentar nomes aproximados).

### ISSUE THREAD

**Issue by jlauber18** [jlauber18/MusicBot#1]
### Is your feature request related to a problem? Please describe.

O comando "lyrics" não possui relação com a música sendo tocada atualmente, portanto é necessário colocar o nome da música para receber sua letra.

### What is your ideal solution to the problem?

Tornar padrão ao utilizar o comando "lyrics" retornar a música atual sem a necessidade de colocar seu nome no comando.

### How would this feature be used?

A música tocando é: "Queen - Under Pressure".
Efetuo a busca da letra sem digitar o nome da música.
A busca retorna a letra da música Under Pressure do Queen.

### Additional Info

História de usuário:
Como usuário, eu quero buscar a letra da música atual sem a necessidade de saber o nome, para que possa conhecê-la e acompanhá-la.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by magsilva** [comment]
Quanto ao exemplo de utilização da funcionalidade, o exemplo parece referente à issue #5. Para esta história de usuário, o exemplo seria usar o comando sem parâmetros, enquanto toca a música, e mostrar a letra da música que está tocando. Outro exemplo seria, ao usar o comando sem parâmetros e sem que uma música esteja tocando, não informar nada ou avisar que não tem uma música tocando nesse instante.
