### ISSUE TITLE
[Feature Request] Buscar a letra de uma música de forma mais precisa.

### ISSUE THREAD

**Issue by JVZavatin** [jlauber18/MusicBot#5]
### Is your feature request related to a problem? Please describe.

Os caracteres especiais e anotações extras no título da música impedem que a letra da música atual seja encontrada pelo comando "lyrics".

### What is your ideal solution to the problem?

Desconsiderar caracteres especiais e buscar também por partes do título para que o melhor resultado  sempre seja mostrado.

### How would this feature be used?

O título da música tocando é: "Queen - Under Pressure (Official Video)".
Efetuo a busca da letra.
A busca ignora o "-" e também o "(Official Video)".
E retorna a letra da música Under Pressure do Queen.

### Additional Info

História de usuário:
Como usuário, eu quero buscar a letra de uma música do youtube de forma precisa, para que não ocorra erros com os caracteres especiais.

### Checklist

- [X] I have checked [the documentation](https://jmusicbot.com/) to make sure this feature doesn't already exist
- [X] I have searched for [similar feature requests](https://github.com/jagrosh/MusicBot/labels/enhancement)
- [X] I have confirmed that my requests is **not** on the [list of things that will not be added](https://jmusicbot.com/things-that-wont-be-added)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by magsilva** [comment]
Quanto a utilização desta funcionalidade, coloque algo mais concreto.  Na verdade, acho que o conteúdo indicado na #1 é adequado para esta história de usuário.

**Comment by jlauber18** [comment]
> 
> 
> Quanto a utilização desta funcionalidade, coloque algo mais concreto. Na verdade, acho que o conteúdo indicado na #1 é adequado para esta história de usuário.

Corrigido.
